In [120]:
from src.kr6 import KR6
import modern_robotics as mr
import numpy as np
from tpk4170.visualization import Viewer
from tpk4170.models import Grid, Axes
from src.dh import DHFrame
import src.tools as tools


In [135]:

r1, r2, r3, r4, a1, a2 = 0, 400, 455, np.sqrt(35**2 + 420**2), 25, 35
køddevinkel = np.arctan2(35, 240)


T_SB = np.array([[0, 0, 1, a1+455+80],
                 [0, 1, 0, 0],
                 [1, 0, 0, r2+a2],
                 [0, 0, 0, 1]])


def pointFromT(T=np.array) -> np.array:
    P = np.zeros(3)
    for i in range(len(T)):
        P[i:] = T[i][3]
    return P

print(pointFromT(T_SB))


def T_SW(T_SB=np.array) -> np.array:
    P_B = pointFromT(T_SB)
    T_BW = np.array([[1, 0, 0, P[0]],
                     [0, 1, 0, P[1]],
                     [0, 0, 1, P[2]+80],
                     [0, 0, 0, 1]])
    return np.dot(T_SB, T_BW)

T_SW = T_SW(T_SB)

print(T_SW)

P_W = pointFromT(T_SW)

print(P_W)

theta1_i = np.arctan2(-P[1], P[0])

theta1_ii = np.arctan2(P[1], -P[0])

Pz, Px, Py = P_W[2], P_W[0] - np.cos(theta1_i) * a1 , P_W[1]+np.sin(theta1_ii) * a1

c3 = (Pz**2 + Px**2 + Py**2 - r3**2 - r4**2) / (2 * r3 * r4)

print(c3)
#c3_ii = ((P_W[2] - (r1+r2))**2 + (P_W[0] - np.cos(theta1_i)*a1)**2 + (P_W[1]+np.sin(theta1_ii) * a1)**2) / (2 * r3 * r4)


s3_pos = np.sqrt(1-c3)
s3_neg = -np.sqrt(1-c3)

theta3_i = np.arctan2(s3_pos, c3)*Pz
theta3_ii = -theta3_i

# dersom s3 er positiv:
theta2_i = np.arctan2((r3+r4*c3)*Pz - r4*s3_pos*np.sqrt(Px **2 + Py**2), (r3+r4)*np.sqrt(Px**2+Py**2)+r4*s3_pos*Pz)
theta2_ii = np.arctan2((r3+r4*c3)*Pz + r4*s3_pos*np.sqrt(Px **2 + Py**2), -(r3+r4)*np.sqrt(Px**2+Py**2)+r4*s3_pos*Pz)

# dersom s3 er negativ:
theta2_iii = np.arctan2((r3+r4*c3)*Pz - r4*s3_neg*np.sqrt(Px **2 + Py**2), (r3+r4)*np.sqrt(Px**2+Py**2)+r4*s3_neg*Pz)
theta2_iv = np.arctan2((r3+r4*c3)*Pz + r4*s3_neg*np.sqrt(Px **2 + Py**2), -(r3+r4)*np.sqrt(Px**2+Py**2)+r4*s3_neg*Pz)


print([theta1_i, theta2_i, theta3_i])
# Alternative kombinasjoner
# 1: (θ1_I,θ2_I,θ3_I)
# 2: (θ1_I,θ2_III,θ3_II)
# 3: (θ1_II,θ2_II,θ3_I)
# 4: (θ1_II,θ2_IV,θ3_II)


[560.   0. 435.]
[[  0.   0.   1. 809.]
 [  0.   1.   0.   6.]
 [  1.   0.   0. 438.]
 [  0.   0.   0.   1.]]
[809.   6. 438.]
1.1590242740467074
[-1.1071487177940904, nan, nan]


C:\Users\PC\AppData\Local\Temp/ipykernel_4120/3934432490.py:48: RuntimeWarning: invalid value encountered in sqrt
  s3_pos = np.sqrt(1-c3)
C:\Users\PC\AppData\Local\Temp/ipykernel_4120/3934432490.py:49: RuntimeWarning: invalid value encountered in sqrt
  s3_neg = -np.sqrt(1-c3)


In [125]:
viewer = Viewer(background="white")
viewer.add(Grid())

config1 = np.array([0, -np.pi/4, np.pi/6, 0, 0, 0])
config2 = np.array([0, -np.pi/2, np.pi/2, 0, 0, 0])
config3 = np.array([0, 0, np.pi/2, 0, 0, 0])

kr6 = KR6(theta=config1)
# kr6.add_FK_to_viewer(viewer)

print(f"Number of iteration: {kr6.IK[3]}")
print(np.allclose(kr6.Tsb_dh, kr6.Tsb_IK, 0.01, 0.01))

kr6.add_nIK_to_viewer(viewer)


C:\Users\PC\anaconda3\envs\tpk4170_venv\lib\site-packages\jupyter_client\session.py:716: UserWarning: Message serialization failed with:
Out of range float values are not JSON compliant
Supporting this message is deprecated in jupyter-client 7, please make sure your message is JSON-compliant
  content = self.pack(content)


Renderer(camera=PerspectiveCamera(aspect=1.5, children=(DirectionalLight(color='white', intensity=0.66, positi…

Number of iteration: 3
True
