In [1]:
from tpk4170.visualization import Ur5Visualizer
from dataclasses import dataclass
import modern_robotics as mr
import numpy as np
from src.kr6 import KR6
from tpk4170.visualization import Viewer
from tpk4170.models import Grid, Axes
from src.dh import DHFrame

np.set_printoptions(suppress=True)

PI_HALF = np.pi / 2
PI = np.pi


In [2]:
config1 = np.array([0,0,0,0,0,0])
config2 = np.array([0,-np.pi/2,np.pi/2,0,0,0])
config3 = np.array([0,0,np.pi/2,0,0,0])
config4 = np.array([0,0,0,0,0,0])
config5 = np.array([0,0,0,0,0,0])

kr6_1 = KR6()
print(np.allclose(kr6_1.Tsb_dh,kr6_1.Tsb_poe,0.01))

kr6 = KR6(config3)
print(kr6.Tsb_dh)
print(kr6.Tsb_poe)

False
[[ 1.  0.  0.  0.]
 [ 0. -1. -0.  0.]
 [ 0.  0. -1.  0.]
 [ 0.  0.  0.  1.]]
[[ 1.     0.     0.     0.515]
 [ 0.    -1.     0.     0.   ]
 [ 0.     0.    -1.    -0.1  ]
 [ 0.     0.     0.     1.   ]]


In [3]:
viewer = Viewer(background="white")
viewer.add(Grid())

viewer.add(Axes(0.1))
kr6.add_FK_to_viewer(viewer)

Renderer(camera=PerspectiveCamera(aspect=1.5, children=(DirectionalLight(color='white', intensity=0.66, positi…