In [15]:
from src.kr6 import KR6
import modern_robotics as mr
import numpy as np
from tpk4170.visualization import Viewer
from tpk4170.models import Grid, Axes
from src.dh import DHFrame
import src.tools as tools
import sympy as sp


In [16]:

T_SB = np.array([[0,  1,   0, 0],
                 [0,  0,  -1, -(0.420+0.025+0.080)],
                 [-1, 0,   0, 0.89],
                 [0,  0,   0, 1]])

#print('forventer at P_W er: \n', tools.pointFromT(tools.makeT_SW(T_SB)))

theta = np.pi/180*np.array([0, -90, 90, 2, 2, 2        + 180])

kr6 = KR6(theta)

S = kr6._Slist

M = kr6._M

thetalists = np.around(kr6.aIK_thetaLists,2)

np.around(thetalists*180/np.pi,1)


array([[   0. ,   -8.6,  -80.2],
       [   0. ,  -90. ,   90. ],
       [-179.9, -171.3,   83.1],
       [-179.9,  -96.3,  -73.9]])

In [21]:
T = kr6.Tsb_poe

print(T)

R_46, R_46sp = tools.inverseKinematicsTheta456(thetalists, T, S, M)

R_46,R_46sp

theta4_i = np.arctan2(R_46[1][2], R_46[0][2])
# theta5_i = np.arctan2(np.sqrt(R_46[0][2]**2 + R_46[1][2]**2), R_46[2][2])
# theta6_i = np.arctan2(R_46[2][1], -R_46[2][0])

# theta4_i





[[-3.48782369e-02 -1.21797487e-03  9.99390827e-01  5.24951266e-01]
 [-6.97352269e-02  9.97564792e-01 -1.21797487e-03 -9.74379896e-05]
 [-9.96955619e-01 -6.97352269e-02 -3.48782369e-02  8.87209741e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


TypeError: 'Float' object is not subscriptable

In [18]:
config_fasit = np.array([0,-np.pi/4, np.pi/6, 0,0,0])
config2 = np.array([0, -np.pi/2, np.pi/2, 0, 0, 0])
config3 = np.array([0, np.pi/2, 0, 0, 0, 0])





# kr6.add_FK_to_viewer(viewer)

# print(f"Number of iteration: {kr6.IK[3]}")

# kr6.add_nIK_to_viewer(viewer)
viewer = Viewer(background="white")
viewer.add(Grid())
KR6(config_fasit).add_FK_to_viewer(viewer)


C:\Users\test\anaconda3\envs\tpk4170_venv\lib\site-packages\jupyter_client\session.py:716: UserWarning: Message serialization failed with:
Out of range float values are not JSON compliant
Supporting this message is deprecated in jupyter-client 7, please make sure your message is JSON-compliant
  content = self.pack(content)


Renderer(camera=PerspectiveCamera(aspect=1.5, children=(DirectionalLight(color='white', intensity=0.66, positi…

c:\Users\test\git\TPK4170_project-1\src\tools.py:177: RuntimeWarning: invalid value encountered in sqrt
  s3_pos = np.sqrt(1-c3**2)
c:\Users\test\git\TPK4170_project-1\src\tools.py:178: RuntimeWarning: invalid value encountered in sqrt
  s3_neg = -np.sqrt(1-c3**2)
