In [4]:
from src.kr6 import KR6
import modern_robotics as mr
import numpy as np
from tpk4170.visualization import Viewer
from tpk4170.models import Grid, Axes
from src.dh import DHFrame
import src.tools as tools
import sympy as sp

In [5]:
# Testing if we get 4 configurations of theta 1,2,3 that results in the same wrist position
theta = np.pi/180*np.array([-45, -90, 90, 0,0,0])

kr6 = KR6(theta) # Creating the robot with the given theta configuration

P_W = tools.pointFromT(kr6.Tsw) # Getting the wrist position

thetalists = np.around(kr6.aIK_thetaLists,2) # Fetching the 4 sets of thetas that should provide the same wrist position as the original input of KR6

np.around(thetalists*180/np.pi,1) # Converting the thetas to degrees and rounding them to 1 decimal place

# testing if the 4 configurations give the same wrist position
for i in thetalists:
    print(np.around(i*180/np.pi,2))
    i = np.append(i,0)
    i = np.append(i,0)
    i = np.append(i,0)
    kr6_test = KR6(i)
    P_W_test = tools.pointFromT(kr6_test.Tsw)
    print(np.allclose(P_W, P_W_test, 0.02))


[-45.26  -8.59 -80.21]
True
[-45.26 -89.95  89.95]
True
[ 135.22 -171.31   83.08]
True
[135.22 -96.26 -73.91]
True


In [6]:
S = kr6._Slist
M = kr6._M
T = kr6.Tsb_poe

tools.inverseKinematicsTheta456(thetalists, T, S, M)

array([[-4.5260e+01, -8.5900e+00, -8.0210e+01, -8.9990e+01,  2.6000e-01,
         1.7974e+02],
       [-4.5260e+01, -8.9950e+01,  8.9950e+01,  0.0000e+00,  0.0000e+00,
        -0.0000e+00],
       [ 1.3522e+02, -1.7131e+02,  8.3080e+01, -8.9990e+01,  2.2000e-01,
         2.2000e-01],
       [ 1.3522e+02, -9.6260e+01, -7.3910e+01, -9.1260e+01,  9.0000e-02,
         2.2000e-01]])