In [1]:
from src.kr6 import KR6
import modern_robotics as mr
import numpy as np
from tpk4170.visualization import Viewer
from tpk4170.models import Grid, Axes
from src.dh import DHFrame
import src.tools as tools
import sympy as sp

# T_SB = np.array([[0,  1,   0, 0],
#                  [0,  0,  -1, -(0.420+0.025+0.080)],
#                  [-1, 0,   0, 0.89],
#                  [0,  0,   0, 1]])


In [2]:
# Testing if we get 4 configurations of theta 1,2,3 that results in the same wrist position

theta = np.pi/180*np.array([-45, -90, 90, 0,0,0])

kr6 = KR6(theta)

P_W = tools.pointFromT(kr6.Tsw)

thetalists = np.around(kr6.aIK_thetaLists,2) #creating the 4 sets of thetas that should provide the same wrist position as the original input of KR6

np.around(thetalists*180/np.pi,1)

for i in thetalists:
    print(np.around(i*180/np.pi,2))
    i = np.append(i,0)
    i = np.append(i,0)
    i = np.append(i,0)
    kr6_test = KR6(i)
    P_W_test = tools.pointFromT(kr6_test.Tsw)
    print(np.allclose(P_W, P_W_test, 0.02))


[-45.26  -8.59 -80.21]
True
[-45.26 -89.95  89.95]
True
[ 135.22 -171.31   83.08]
True
[135.22 -96.26 -73.91]
True


In [3]:

S = kr6._Slist

M = kr6._M

T = kr6.Tsb_poe



tools.inverseKinematicsTheta456(thetalists, T, S, M)




[-45.3  -8.6 -80.2 -90.    0.3 179.7]
[-45.3 -90.   90.    0.    0.   -0. ]
[ 135.2 -171.3   83.1  -90.     0.2    0.2]
[ 1.352e+02 -9.630e+01 -7.390e+01 -9.130e+01  1.000e-01  2.000e-01]


In [4]:
config_fasit = np.array([0,-np.pi/4, np.pi/6, 0,0,0])
config2 = np.array([0, -np.pi/2, np.pi/2, 0, 0, 0])
config3 = np.array([0, np.pi/2, 0, 0, 0, 0])





# kr6.add_FK_to_viewer(viewer)

# print(f"Number of iteration: {kr6.IK[3]}")

# kr6.add_nIK_to_viewer(viewer)
viewer = Viewer(background="white")
viewer.add(Grid())
KR6(theta).add_FK_to_viewer(viewer)


C:\Users\PC\anaconda3\envs\tpk4170_venv\lib\site-packages\jupyter_client\session.py:716: UserWarning: Message serialization failed with:
Out of range float values are not JSON compliant
Supporting this message is deprecated in jupyter-client 7, please make sure your message is JSON-compliant
  content = self.pack(content)


Renderer(camera=PerspectiveCamera(aspect=1.5, children=(DirectionalLight(color='white', intensity=0.66, positi…