In [1]:
from src.kr6 import KR6
import modern_robotics as mr
import numpy as np
from tpk4170.visualization import Viewer
from tpk4170.models import Grid, Axes
from src.dh import DHFrame
import src.tools as tools
import sympy as sp


In [2]:

r1, r2, r3, r4, a1, a2 = 0, 0.400, 0.455, 10**(-3)*np.sqrt(420**2+35**2), 0.025, 0.035
køddevinkel = np.arctan2(35, 420)


T_SB = np.array([[0,  0, 1, 0.420+0.025+0.080],
                 [0, -1, 0, 0],
                 [1,  0, 0, 0.89],
                 [0,  0, 0, 1]])


print('forventer at P_W er: \n', tools.pointFromT(tools.makeT_SW(T_SB)))



sp.Matrix((tools.inverseKinematicsTheta123(T_SB)))




forventer at P_W er: 
 [0.445 0.    0.89 ]
T_SW: 
 [[ 1.     0.     0.     0.445]
 [ 0.    -1.     0.     0.   ]
 [ 0.     0.     1.     0.89 ]
 [ 0.     0.     0.     1.   ]] 
P_W:  [0.445 0.    0.89 ]
1.4876550949064553
-1.4876550949064553 1.4876550949064553


Matrix([
[    0, 8.79741070999109, -85.2363583092738],
[    0,            -90.0,              90.0],
[180.0, 8.79741070999109, -85.2363583092738],
[180.0,             90.0,  85.2363583092738]])

In [3]:

config_fasit = np.array([0,-np.pi/4, np.pi/6, 0,0,0])

config2 = np.array([0, -np.pi/2, np.pi/2, 0, 0, 0])
config3 = np.array([0, np.pi/2, 0, 0, 0, 0])




def test_a_IK(config_fasit):

    kr6_fasit = KR6(config_fasit)

    P_SW_fasit = tools.pointFromT(kr6_fasit.Tsw) # define the point of the wrist

    thetalist = kr6_fasit.aIK_thetaLists # Fetching the analytical solution(s)

    for el in thetalist:
        config_test = np.array([el[0], el[1], el[2], 0,0,0])

        kr6_test = KR6(config_test)

        P_SW_test = tools.pointFromT(kr6_test.Tsw)

        print(kr6_fasit.Tsb_poe)
        # print(kr6_fasit.Tsw)
        print(P_SW_test)
        print(P_SW_fasit)

        print(np.allclose(P_SW_fasit, P_SW_test, 0.01, 0.01))

print(test_a_IK(np.array([0, 0, 0, 0, 0, 0])))

# kr6.add_FK_to_viewer(viewer)

# print(f"Number of iteration: {kr6.IK[3]}")

# kr6.add_nIK_to_viewer(viewer)
viewer = Viewer(background="white")
viewer.add(Grid())
KR6(config_fasit).add_FK_to_viewer(viewer)


T_SW: 
 [[ 1.00000000e+00 -1.83697020e-16  6.12323400e-17  9.00000000e-01]
 [-1.83697020e-16 -1.00000000e+00  1.83697020e-16  3.94948593e-17]
 [-6.12323400e-17  1.83697020e-16  1.00000000e+00  4.35000000e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]] 
P_W:  [9.00000000e-01 3.94948593e-17 4.35000000e-01]
0.08314123188843929
-0.0831412318884393 0.0831412318884393
T_SW: 
 [[ 5.12294219e-02  2.50491014e-15  9.98686911e-01  5.36470399e-01]
 [-2.38345627e-16 -1.00000000e+00  2.52043000e-15  1.30520203e-15]
 [-9.98686911e-01  3.67152829e-16  5.12294219e-02 -1.76558614e-02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]] 
P_W:  [ 5.36470399e-01  1.30520203e-15 -1.76558614e-02]
1.4364023845650782
-1.4364023845650782 1.4364023845650782
[[ 0.     0.     1.     0.98 ]
 [ 0.    -1.     0.     0.   ]
 [ 1.     0.     0.     0.435]
 [ 0.     0.     0.     1.   ]]
[ 0.53647041  0.         -0.0176554 ]
[0.9   0.    0.435]
False
T_SW: 
 [[ 2.31553534e-01  2.

C:\Users\test\anaconda3\envs\tpk4170_venv\lib\site-packages\jupyter_client\session.py:716: UserWarning: Message serialization failed with:
Out of range float values are not JSON compliant
Supporting this message is deprecated in jupyter-client 7, please make sure your message is JSON-compliant
  content = self.pack(content)


Renderer(camera=PerspectiveCamera(aspect=1.5, children=(DirectionalLight(color='white', intensity=0.66, positi…

T_SW: 
 [[ 9.65925826e-01 -1.77437696e-16 -2.58819045e-01  7.43363766e-01]
 [-1.36152733e-16 -1.00000000e+00  1.77437696e-16  1.18345884e-16]
 [ 2.58819045e-01  1.36152733e-16  9.65925826e-01  8.64244988e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]] 
P_W:  [7.43363766e-01 1.18345884e-16 8.64244988e-01]
0.44045754370985635
-0.4404575437098564 0.4404575437098564
