In [1]:
from src.kr6 import KR6
import modern_robotics as mr
import numpy as np
from tpk4170.visualization import Viewer
from tpk4170.models import Grid, Axes
from src.dh import DHFrame
import src.tools as tools
import sympy as sp


In [2]:

# r1, r2, r3, r4, a1, a2 = 0, 0.400, 0.455, 10**(-3)*np.sqrt(420**2+35**2), 0.025, 0.035
# køddevinkel = np.arctan2(35, 420)

T_SB = np.array([[0,  1,   0, 0],
                 [0,  0,  -1, -(0.420+0.025+0.080)],
                 [-1, 0,   0, 0.89],
                 [0,  0,   0, 1]])

#print('forventer at P_W er: \n', tools.pointFromT(tools.makeT_SW(T_SB)))

theta = np.pi/180*np.array([0, -90, 90, 0, 0, 0])

kr6 = KR6(theta)

thetalists = np.around(kr6.aIK_thetaLists,2)

thetalists



array([[-0.  , -0.15, -1.4 ],
       [-0.  , -1.57,  1.57],
       [ 3.14, -2.99,  1.45],
       [ 3.14, -1.68, -1.29]])

In [3]:
M = kr6._M

S = kr6._Slist
tools.inverseKinematicsTheta456(thetalists)

[[ 1.  0.  0.]
 [ 0. -0.  1.]
 [ 0. -1. -0.]]


In [4]:
config_fasit = np.array([0,-np.pi/4, np.pi/6, 0,0,0])
config2 = np.array([0, -np.pi/2, np.pi/2, 0, 0, 0])
config3 = np.array([0, np.pi/2, 0, 0, 0, 0])





# kr6.add_FK_to_viewer(viewer)

# print(f"Number of iteration: {kr6.IK[3]}")

# kr6.add_nIK_to_viewer(viewer)
viewer = Viewer(background="white")
viewer.add(Grid())
KR6(config_fasit).add_FK_to_viewer(viewer)


C:\Users\test\anaconda3\envs\tpk4170_venv\lib\site-packages\jupyter_client\session.py:716: UserWarning: Message serialization failed with:
Out of range float values are not JSON compliant
Supporting this message is deprecated in jupyter-client 7, please make sure your message is JSON-compliant
  content = self.pack(content)


Renderer(camera=PerspectiveCamera(aspect=1.5, children=(DirectionalLight(color='white', intensity=0.66, positi…

c:\Users\test\git\TPK4170_project-1\src\tools.py:157: RuntimeWarning: invalid value encountered in sqrt
  s3_pos = np.sqrt(1-c3**2)
c:\Users\test\git\TPK4170_project-1\src\tools.py:158: RuntimeWarning: invalid value encountered in sqrt
  s3_neg = -np.sqrt(1-c3**2)
