In [1]:
from src.kr6 import KR6
import modern_robotics as mr
import numpy as np
from tpk4170.visualization import Viewer
from tpk4170.models import Grid, Axes
from src.dh import DHFrame
import src.tools as tools
import sympy as sp


In [9]:

r1, r2, r3, r4, a1, a2 = 0, 0.400, 0.455, 10**(-3)*np.sqrt(420**2+35**2), 0.025, 0.035
køddevinkel = np.arctan2(35, 420)

T_SB = np.array([[0,  1,   0, 0],
                 [0,  0,  -1, -(0.420+0.025+0.080)],
                 [-1, 0,   0, 0.89],
                 [0,  0,   0, 1]])

#print('forventer at P_W er: \n', tools.pointFromT(tools.makeT_SW(T_SB)))

sp.Matrix((np.around(tools.inverseKinematicsTheta123(T_SB),1)))

theta = np.pi/180*np.array([-45, -90, 90, 0, 0, 0])
 
kr6 = KR6(theta)

T = kr6.Tsb_IK

sp.Matrix(T)

# T = np.array([[0,  -0.5,   -0.5, 0.371231],
#               [0,   0.5,    0,   0.371231],
#               [1,    0,   -0.5, 890],
#               [0,     0,    0,   1]])

# print(tools.pointFromT(T))

# sp.Matrix(T)

sp.Matrix((np.around(tools.inverseKinematicsTheta123(T),1)))

1.5707963267948966
1.4876550949064553
-0.7853981633974485
1.4876550949064555
-0.7853389022605982
1.4881618177246503


Matrix([
[-45.0,   -8.8, -80.5],
[-45.0,  -90.0,  90.0],
[135.0, -171.3,  83.3],
[135.0,  -96.3, -73.8]])

In [3]:
config_fasit = np.array([0,-np.pi/4, np.pi/6, 0,0,0])
config2 = np.array([0, -np.pi/2, np.pi/2, 0, 0, 0])
config3 = np.array([0, np.pi/2, 0, 0, 0, 0])




def test_a_IK(config_fasit):

    kr6_fasit = KR6(config_fasit)

    P_SW_fasit = tools.pointFromT(kr6_fasit.Tsw) # define the point of the wrist

    thetalist = kr6_fasit.aIK_thetaLists # Fetching the analytical solution(s)

    for el in thetalist:
        config_test = np.array([el[0], el[1], el[2], 0,0,0])

        kr6_test = KR6(config_test)

        P_SW_test = tools.pointFromT(kr6_test.Tsw)

        print(kr6_fasit.Tsb_poe)
        # print(kr6_fasit.Tsw)
        print(P_SW_test)
        print(P_SW_fasit)

        print(np.allclose(P_SW_fasit, P_SW_test, 0.01, 0.01))

print(test_a_IK(np.array([0, 0, 0, 0, 0, 0])))

# kr6.add_FK_to_viewer(viewer)

# print(f"Number of iteration: {kr6.IK[3]}")

# kr6.add_nIK_to_viewer(viewer)
viewer = Viewer(background="white")
viewer.add(Grid())
KR6(config_fasit).add_FK_to_viewer(viewer)


-4.3883176969446814e-17
0.08314123188843929
-2.5582040089444443e-15
0.083141231888331
[[ 0.     0.     1.     0.98 ]
 [ 0.    -1.     0.     0.   ]
 [ 1.     0.     0.     0.435]
 [ 0.     0.     0.     1.   ]]
[0.9   0.    0.435]
[0.9   0.    0.435]
True
-3.4464682009011313e-15
3.1222284647953695
[[ 0.     0.     1.     0.98 ]
 [ 0.    -1.     0.     0.   ]
 [ 1.     0.     0.     0.435]
 [ 0.     0.     0.     1.   ]]
[0.02869285 0.         0.36559827]
[0.9   0.    0.435]
False
nan
nan
[[ 0.     0.     1.     0.98 ]
 [ 0.    -1.     0.     0.   ]
 [ 1.     0.     0.     0.435]
 [ 0.     0.     0.     1.   ]]
[nan nan nan]
[0.9   0.    0.435]
False
nan

c:\Users\test\git\TPK4170_project-1\src\tools.py:163: RuntimeWarning: invalid value encountered in sqrt
  s3_pos = np.sqrt(1-c3**2)
c:\Users\test\git\TPK4170_project-1\src\tools.py:164: RuntimeWarning: invalid value encountered in sqrt
  s3_neg = -np.sqrt(1-c3**2)



nan
[[ 0.     0.     1.     0.98 ]
 [ 0.    -1.     0.     0.   ]
 [ 1.     0.     0.     0.435]
 [ 0.     0.     0.     1.   ]]
[nan nan nan]
[0.9   0.    0.435]
False
None


C:\Users\test\anaconda3\envs\tpk4170_venv\lib\site-packages\jupyter_client\session.py:716: UserWarning: Message serialization failed with:
Out of range float values are not JSON compliant
Supporting this message is deprecated in jupyter-client 7, please make sure your message is JSON-compliant
  content = self.pack(content)


Renderer(camera=PerspectiveCamera(aspect=1.5, children=(DirectionalLight(color='white', intensity=0.66, positi…

-1.5920319209411077e-16
0.44045754370985635
