In [1]:
from src.kr6 import KR6
import modern_robotics as mr
import numpy as np
from tpk4170.visualization import Viewer
from tpk4170.models import Grid, Axes
from src.dh import DHFrame
import src.tools as tools
import sympy as sp

In [2]:
kr6 = KR6()
thetas = tools.inverseKinematicsTheta123(kr6.Tsb_poe)

c:\Users\Bendik\Documents\Git\TPK4170_project\src\tools.py:177: RuntimeWarning: invalid value encountered in sqrt
  s3_pos = np.sqrt(1-c3**2)
c:\Users\Bendik\Documents\Git\TPK4170_project\src\tools.py:178: RuntimeWarning: invalid value encountered in sqrt
  s3_neg = -np.sqrt(1-c3**2)


In [22]:
ths = tools.inverseKinematicsTheta456(thetalists= thetas, T_SB= kr6.Tsb_poe)

In [24]:
# ths = np.rad2deg(ths)
# ths = np.around(ths, decimals=8)
ths

[array([-0.00000000e+00, -9.59148143e-16,  1.91513472e-15,  6.01232834e-02,
         3.14159265e+00, -3.08146937e+00]),
 array([-0.00000000e+00, -7.99573742e-02,  1.66282464e-01,  7.07559796e-16,
         3.05526756e+00, -3.14159265e+00]),
 array([3.14159265,        nan,        nan,        nan,        nan,
               nan]),
 array([3.14159265,        nan,        nan,        nan,        nan,
               nan])]